# Cloudflare Pages configuration
name = "wallet-api-docs"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

# Build settings (Cloudflare Pages will use these)
[build]
command = "npm run build"
